import type { Arms, Face, Icon, Legs, Scene } from "./art";

export interface Dare {
  id: string;
  text: string;
  seconds: number;
  /** Shared objects. Two dares with the same prop are not paired if another dare is available. */
  prop: string | null;
  propLabel: string | null;
  /** Silly-gross living-room humor. Pretend, a noise, or your own shoe. Never a real mess. */
  gross: boolean;
  scene: Scene;
}

interface Seed {
  id: string;
  text: string;
  seconds: number;
  prop?: string;
  propLabel?: string;
  gross?: boolean;
  face: Face;
  arms: Arms;
  legs: Legs;
  icon?: Icon;
}

const LOOKS: Array<[string, string, string]> = [
  ["#8fd3f4", "#7bc98a", "#ff5d3a"],
  ["#ffe066", "#f4a261", "#4361ee"],
  ["#d4b3ff", "#95d5b2", "#ef476f"],
  ["#ffc2d4", "#c9f2c7", "#5c4d7a"],
  ["#b8f2e6", "#ffe8a3", "#e85d04"],
  ["#cde7ff", "#ffd6a5", "#0a9396"],
  ["#fff1a8", "#f4a261", "#7209b7"],
  ["#ffd6e0", "#90e0ef", "#f77f00"],
  ["#e0fbfc", "#ee9b00", "#9b2226"],
  ["#fde2e4", "#b5e48c", "#1d3557"],
];

const SEEDS: Seed[] = [
  {
    id: "jacks",
    text: "Do 10 jumping jacks and count every one out loud.",
    seconds: 15,
    face: "grin",
    arms: "up",
    legs: "split",
    icon: "star",
  },
  {
    id: "dizzy",
    text: "Spin around three times, then walk a straight line. Stop if you feel woozy.",
    seconds: 18,
    face: "wow",
    arms: "out",
    legs: "stand",
  },
  {
    id: "hop",
    text: "Hop on one foot to the far side of the room and back.",
    seconds: 15,
    face: "grin",
    arms: "one-up",
    legs: "hop",
  },
  {
    id: "crab",
    text: "Crab-walk to the nearest wall and back.",
    seconds: 18,
    face: "grin",
    arms: "down",
    legs: "crab",
  },
  {
    id: "chicken",
    text: "Do the chicken dance until the timer ends.",
    seconds: 15,
    face: "grin",
    arms: "wave",
    legs: "hop",
  },
  {
    id: "quack",
    text: "Quack and flap like a duck until the timer ends.",
    seconds: 12,
    face: "ooh",
    arms: "wave",
    legs: "waddle",
    icon: "duck",
  },
  {
    id: "robot",
    text: "Talk only in a robot voice until the timer ends.",
    seconds: 15,
    face: "robot",
    arms: "down",
    legs: "stand",
  },
  {
    id: "questions",
    text: "You may only ask questions until the timer ends.",
    seconds: 18,
    face: "ooh",
    arms: "one-up",
    legs: "stand",
    icon: "question",
  },
  {
    id: "pillow",
    text: "Balance a pillow on your head and parade around the room.",
    seconds: 18,
    prop: "pillow",
    propLabel: "Needs a pillow",
    face: "focus",
    arms: "out",
    legs: "stand",
    icon: "pillow",
  },
  {
    id: "statue",
    text: "Freeze like a statue. Everyone else can try to make you laugh.",
    seconds: 20,
    face: "focus",
    arms: "akimbo",
    legs: "stand",
  },
  {
    id: "draw-eyes",
    text: "Close your eyes and draw a cat. Keep them closed until the timer ends.",
    seconds: 20,
    prop: "paper",
    propLabel: "Needs paper and a pencil",
    face: "shut",
    arms: "one-up",
    legs: "stand",
    icon: "paper",
  },
  {
    id: "draw-foot",
    text: "Draw a smiley face using your foot.",
    seconds: 20,
    prop: "paper",
    propLabel: "Needs paper and a pencil",
    face: "focus",
    arms: "out",
    legs: "hop",
    icon: "paper",
  },
  {
    id: "highfive",
    text: "High-five every person in the room. Solo? High-five the air with style.",
    seconds: 12,
    face: "grin",
    arms: "one-up",
    legs: "stand",
  },
  {
    id: "bow",
    text: 'Give every player a royal bow and say "Your Majesty."',
    seconds: 15,
    face: "smug",
    arms: "down",
    legs: "stand",
    icon: "crown",
  },
  {
    id: "checkers",
    text: "Speed checkers until the buzzer. No board? Slide coins on the rug and call the jumps.",
    seconds: 45,
    prop: "board",
    propLabel: "Uses a board, or mime it",
    face: "focus",
    arms: "down",
    legs: "sit",
    icon: "board",
  },
  {
    id: "chess",
    text: "Make three chess moves and announce each one like a sports caster. No board? Narrate an invisible match.",
    seconds: 40,
    prop: "board",
    propLabel: "Uses a board, or mime it",
    face: "smug",
    arms: "one-up",
    legs: "sit",
    icon: "board",
  },
  {
    id: "stack",
    text: "Stack five unbreakable things into a tower, then take one step back.",
    seconds: 20,
    prop: "stack",
    propLabel: "Needs 5 safe things",
    face: "focus",
    arms: "up",
    legs: "stand",
    icon: "stack",
  },
  {
    id: "fort",
    text: "Build a pillow fort big enough to fit your head.",
    seconds: 20,
    prop: "pillow",
    propLabel: "Needs a pillow",
    face: "grin",
    arms: "out",
    legs: "stand",
    icon: "fort",
  },
  {
    id: "whisper",
    text: "Whisper a real compliment to every other player. Solo? Compliment your own hair.",
    seconds: 18,
    face: "ooh",
    arms: "one-up",
    legs: "stand",
  },
  {
    id: "color",
    text: "Shout your favorite color three times like a whole stadium.",
    seconds: 12,
    face: "wow",
    arms: "up",
    legs: "jump",
  },
  {
    id: "march",
    text: "March in place like a parade leader and salute the room.",
    seconds: 15,
    face: "smug",
    arms: "wave",
    legs: "stand",
  },
  {
    id: "silly-walk",
    text: "Cross the room using your silliest walk.",
    seconds: 15,
    face: "grin",
    arms: "wave",
    legs: "split",
  },
  {
    id: "pat-rub",
    text: "Pat your head and rub your belly until the timer ends.",
    seconds: 12,
    face: "focus",
    arms: "one-up",
    legs: "stand",
  },
  {
    id: "mouse",
    text: "Talk in a squeaky mouse voice until the timer ends.",
    seconds: 15,
    face: "ooh",
    arms: "up",
    legs: "stand",
  },
  {
    id: "nature",
    text: "Narrate everything you do like a nature documentary.",
    seconds: 18,
    face: "smug",
    arms: "out",
    legs: "stand",
  },
  {
    id: "tada",
    text: 'Do five star jumps and yell "TA-DA!" after each one.',
    seconds: 15,
    face: "wow",
    arms: "up",
    legs: "jump",
    icon: "star",
  },
  {
    id: "ballet",
    text: "Tiptoe to the door and back with huge ballet arms.",
    seconds: 15,
    face: "smug",
    arms: "up",
    legs: "hop",
  },
  {
    id: "hero",
    text: "Invent a superhero name, strike the pose, and hold it.",
    seconds: 12,
    face: "smug",
    arms: "akimbo",
    legs: "split",
    icon: "star",
  },
  {
    id: "alphabet",
    text: "Sing the alphabet to the tune of a totally different song.",
    seconds: 18,
    face: "grin",
    arms: "out",
    legs: "stand",
  },
  {
    id: "weather",
    text: "Give a serious weather report about this living room.",
    seconds: 15,
    face: "focus",
    arms: "one-up",
    legs: "stand",
  },
  {
    id: "penguin",
    text: "Waddle one full lap of the room like a penguin.",
    seconds: 15,
    face: "smug",
    arms: "down",
    legs: "waddle",
  },
  {
    id: "lava",
    text: "The floor is lava. Reach the couch on rugs or cushions, and leave wobbly things alone.",
    seconds: 15,
    face: "wow",
    arms: "up",
    legs: "hop",
  },
  {
    id: "furniture",
    text: "Give a thank-you speech to the couch like it just won a prize.",
    seconds: 15,
    face: "grin",
    arms: "out",
    legs: "stand",
  },
  {
    id: "slowmo",
    text: "Pretend to pour a drink in super slow motion.",
    seconds: 15,
    face: "ooh",
    arms: "out",
    legs: "stand",
  },
  {
    id: "bunny",
    text: 'Hop like a bunny and say "boing" on every single hop.',
    seconds: 12,
    face: "grin",
    arms: "up",
    legs: "hop",
  },
  {
    id: "balloon",
    text: "Keep an imaginary balloon in the air until the timer ends.",
    seconds: 15,
    face: "wow",
    arms: "one-up",
    legs: "stand",
    icon: "balloon",
  },
  {
    id: "opera",
    text: 'Sing "I am sitting in the living room" in your biggest opera voice.',
    seconds: 15,
    face: "wow",
    arms: "out",
    legs: "stand",
  },
  {
    id: "mirror",
    text: "Copy the player on your left like a mirror. Playing solo? Copy the nearest lamp.",
    seconds: 15,
    face: "focus",
    arms: "wave",
    legs: "stand",
  },
  {
    id: "cowboy",
    text: "Announce your rodeo name and gallop in a circle.",
    seconds: 15,
    face: "grin",
    arms: "one-up",
    legs: "split",
    icon: "star",
  },
  {
    id: "handshake",
    text: "Invent a secret handshake and teach it to someone. Solo? Teach the couch.",
    seconds: 18,
    face: "grin",
    arms: "out",
    legs: "stand",
  },
  {
    id: "pirate",
    text: "Talk like a pirate and declare three things in this room to be treasure.",
    seconds: 15,
    face: "smug",
    arms: "akimbo",
    legs: "stand",
    icon: "crown",
  },
  {
    id: "conductor",
    text: "Conduct an invisible orchestra until the timer ends. The room may hum along.",
    seconds: 15,
    face: "focus",
    arms: "up",
    legs: "stand",
  },
  {
    id: "booger",
    text: "Pretend to pick a booger and flick it across the room. Imaginary boogers only.",
    seconds: 12,
    gross: true,
    face: "bleh",
    arms: "one-up",
    legs: "stand",
  },
  {
    id: "tongue",
    text: "Talk with your tongue sticking out until the timer ends.",
    seconds: 15,
    gross: true,
    face: "tongue",
    arms: "down",
    legs: "stand",
  },
  {
    id: "shoe-score",
    text: "Smell your own shoe and give it a score from one to ten.",
    seconds: 12,
    gross: true,
    prop: "footwear",
    propLabel: "Needs your shoe",
    face: "gag",
    arms: "one-up",
    legs: "stand",
    icon: "shoe",
  },
  {
    id: "blame-dog",
    text: "Make a fart noise with your mouth, then blame the dog. No dog? Blame the couch.",
    seconds: 12,
    gross: true,
    face: "smug",
    arms: "out",
    legs: "stand",
    icon: "puff",
  },
  {
    id: "lick-elbow",
    text: "Try to lick your own elbow. Keep trying until the timer ends.",
    seconds: 15,
    gross: true,
    face: "tongue",
    arms: "one-up",
    legs: "stand",
  },
  {
    id: "armpit",
    text: "Make an armpit noise, or your best mouth copy of one.",
    seconds: 12,
    gross: true,
    face: "bleh",
    arms: "up",
    legs: "stand",
  },
  {
    id: "gag-face",
    text: "Hold your silliest gag face and try not to laugh.",
    seconds: 12,
    gross: true,
    face: "gag",
    arms: "akimbo",
    legs: "stand",
  },
  {
    id: "imaginary-bug",
    text: "Pretend to eat an imaginary bug and chew it as loudly as you can.",
    seconds: 12,
    gross: true,
    face: "bleh",
    arms: "one-up",
    legs: "stand",
    icon: "bug",
  },
  {
    id: "sneeze-elbow",
    text: "Pretend to sneeze into your elbow, then apologize to your elbow.",
    seconds: 12,
    gross: true,
    face: "shut",
    arms: "one-up",
    legs: "stand",
  },
  {
    id: "armpit-flavor",
    text: "Sniff your own armpit and announce the flavor like a fancy food judge.",
    seconds: 12,
    gross: true,
    face: "gag",
    arms: "up",
    legs: "stand",
  },
  {
    id: "whoopee",
    text: "Sit down, make a whoopee-cushion noise with your mouth, and look shocked.",
    seconds: 12,
    gross: true,
    face: "wow",
    arms: "up",
    legs: "sit",
    icon: "puff",
  },
  {
    id: "pretend-burp",
    text: 'Make a big pretend burp with your mouth, then say "Excuse me, that was delicious."',
    seconds: 12,
    gross: true,
    face: "ooh",
    arms: "down",
    legs: "stand",
    icon: "puff",
  },
  {
    id: "toe-names",
    text: "Wiggle your toes at the room and introduce each toe by name.",
    seconds: 15,
    gross: true,
    face: "grin",
    arms: "out",
    legs: "sit",
  },
  {
    id: "hair-in-snack",
    text: "Pretend you found a long hair in your snack. Hold it up and inspect it.",
    seconds: 12,
    gross: true,
    face: "gag",
    arms: "one-up",
    legs: "stand",
  },
  {
    id: "dog-scratch",
    text: "Scratch behind your ear like a dog, sniff your hand, and nod.",
    seconds: 12,
    gross: true,
    face: "smug",
    arms: "one-up",
    legs: "stand",
  },
  {
    id: "dragon-breath",
    text: "Fan the air in front of your mouth like your breath could melt a castle.",
    seconds: 12,
    gross: true,
    face: "bleh",
    arms: "out",
    legs: "stand",
    icon: "puff",
  },
  {
    id: "mud-march",
    text: "March in place and make the squelchiest mud sounds with your mouth.",
    seconds: 15,
    gross: true,
    face: "bleh",
    arms: "wave",
    legs: "stand",
  },
  {
    id: "squish-step",
    text: "Pretend you stepped in something squishy, check your shoe, and react.",
    seconds: 12,
    gross: true,
    prop: "footwear",
    propLabel: "Needs your shoe",
    face: "wow",
    arms: "down",
    legs: "hop",
    icon: "shoe",
  },
  {
    id: "nostril-flare",
    text: "Flare your nostrils as wide as they go and keep them flared.",
    seconds: 12,
    gross: true,
    face: "focus",
    arms: "akimbo",
    legs: "stand",
  },
  {
    id: "ceiling-raspberry",
    text: "Blow a raspberry at the ceiling with your tongue. Aim up, away from people.",
    seconds: 10,
    gross: true,
    face: "tongue",
    arms: "up",
    legs: "stand",
  },
  {
    id: "sock-mystery",
    text: "Smell your own sock and announce whether it is a meadow or a mystery.",
    seconds: 12,
    gross: true,
    prop: "footwear",
    propLabel: "Needs a sock",
    face: "gag",
    arms: "one-up",
    legs: "sit",
    icon: "sock",
  },
];

export const DARES: Dare[] = SEEDS.map((seed, index) => {
  const [sky, hill, shirt] = LOOKS[index % LOOKS.length]!;
  return {
    id: seed.id,
    text: seed.text,
    seconds: seed.seconds,
    prop: seed.prop ?? null,
    propLabel: seed.propLabel ?? null,
    gross: seed.gross ?? false,
    scene: {
      sky,
      hill,
      shirt,
      face: seed.face,
      arms: seed.arms,
      legs: seed.legs,
      prop: seed.icon ?? "none",
    },
  };
});
